/* Writes src/colourIndex.js from the export.
 *
 *     node server/colordb/build-index.js        (load.sh runs it for you)
 *
 * src/carModels.js:8 argues that the vehicle catalogue is a file and not
 * Postgres, because putting it there would force a trip to the server -- and
 * having a server -- just to fill two selects. That argument is right, and
 * this file is how it keeps being right: the makes and their models ship as
 * one static file, so the make and model selects stay synchronous and the
 * network is touched only for colour lists, which at 693,636 rows it has to be.
 *
 * Reads export/, not the database, so it describes exactly what was published.
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const HERE = __dirname;
const EXPORT = path.join(HERE, 'export');
const TARGET = path.join(HERE, '..', '..', 'src', 'colourIndex.js');

/* Minimal CSV reader: the export is ours, one row per line, quotes only where
 * a field holds a comma or a quote. */
function readCsv(file) {
    const text = fs.readFileSync(path.join(EXPORT, file), 'utf8');
    const rows = [];
    let row = [];
    let field = '';
    let quoted = false;
    for (let i = 0; i < text.length; i += 1) {
        const ch = text[i];
        if (quoted) {
            if (ch === '"') {
                if (text[i + 1] === '"') { field += '"'; i += 1; } else quoted = false;
            } else field += ch;
        } else if (ch === '"') quoted = true;
        else if (ch === ',') { row.push(field); field = ''; }
        else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
        else if (ch !== '\r') field += ch;
    }
    if (field || row.length) { row.push(field); rows.push(row); }
    const head = rows.shift();
    return rows.filter((r) => r.length === head.length)
        .map((r) => Object.fromEntries(head.map((h, i) => [h, r[i]])));
}

const makes = readCsv('make.csv');
const models = readCsv('model.csv');
const meta = readCsv('meta.csv')[0];

// Only the groups a customer picks from: the aliases exist so the links fold
// onto one brand, and they have nothing to say to the page.
const groups = makes
    .filter((m) => m.is_vehicle === 't' && m.make_id === m.group_id)
    .map((m) => [Number(m.make_id), m.label, Number(m.sort_key)])
    .sort((a, b) => a[2] - b[2] || a[1].localeCompare(b[1], 'es'));

const known = new Set(groups.map((g) => g[0]));
const byGroup = new Map();
for (const row of models) {
    const g = Number(row.group_id);
    if (!known.has(g)) continue;
    if (!byGroup.has(g)) byGroup.set(g, []);
    byGroup.get(g).push([Number(row.model_id), row.name]);
}
for (const list of byGroup.values()) list.sort((a, b) => a[1].localeCompare(b[1], 'es'));

const payload = {
    version: meta.source_version,
    makes: groups,
    models: Object.fromEntries([...byGroup].map(([g, list]) => [g, list])),
};

const js = `/* The makes and models of the colour database. Generated by
 * server/colordb/build-index.js from its export -- do not edit by hand.
 *
 * Source data ${payload.version}. ${groups.length} makes, ${models.length} models.
 *
 * It ships as a file so the two selects on the matizado page stay synchronous,
 * for the reason src/carModels.js:8 gives. Colours are the part that has to
 * come over the network; these do not.
 */
window.AUTOCOLOR_COLOUR_INDEX = ${JSON.stringify(payload)};
`;

fs.writeFileSync(TARGET, js);
const kb = (Buffer.byteLength(js) / 1024).toFixed(1);
console.log(`src/colourIndex.js: ${groups.length} makes, ${models.length} models, ${kb} KB`);
